# Generated by Django 4.0.5 on 2022-08-30 08:51

import MM.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('JEType', models.CharField(max_length=2)),
                ('sumAmount', models.IntegerField()),
                ('postDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('sector', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11, validators=[MM.models.validate_phone])),
                ('question1', models.CharField(max_length=50)),
                ('answer1', models.CharField(max_length=50)),
                ('question2', models.CharField(max_length=50)),
                ('answer2', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=5, unique=True)),
                ('shortText', models.CharField(blank=True, default='', max_length=20)),
                ('mType', models.CharField(max_length=5)),
                ('mGroup', models.CharField(max_length=4)),
                ('meaunit', models.CharField(max_length=3)),
                ('netWeight', models.IntegerField(default=0)),
                ('weightUnit', models.CharField(max_length=3)),
                ('transGrp', models.CharField(blank=True, max_length=1, null=True)),
                ('loadingGrp', models.CharField(blank=True, max_length=1, null=True)),
                ('industrySector', models.CharField(max_length=1)),
                ('euser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.euser')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sloc', models.CharField(max_length=4)),
                ('sOrg', models.CharField(max_length=4)),
                ('distrChannel', models.CharField(choices=[('I', 'IN'), ('W', 'WH')], max_length=1)),
                ('unrestrictUse', models.IntegerField(default=0)),
                ('blocked', models.IntegerField(default=0)),
                ('qltyInspection', models.IntegerField(default=0)),
                ('transit', models.IntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.material')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('euser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.euser')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=4)),
                ('client', models.CharField(default='MIDEA', max_length=20)),
                ('companyCode', models.CharField(max_length=4)),
                ('pOrg', models.CharField(max_length=4)),
                ('pGrp', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('vname', models.CharField(max_length=20, unique=True)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('postcode', models.CharField(max_length=6, validators=[MM.models.validate_digit])),
                ('country', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=10)),
                ('glAcount', models.CharField(max_length=6)),
                ('phone', models.CharField(blank=True, max_length=11, null=True, validators=[MM.models.validate_phone])),
                ('fax', models.CharField(blank=True, max_length=10, null=True, validators=[MM.models.validate_digit])),
                ('tpType', models.CharField(blank=True, max_length=1, null=True)),
                ('companyCode', models.CharField(max_length=4)),
                ('pOrg', models.CharField(max_length=4)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('score', models.IntegerField(default=100)),
                ('euser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.euser')),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('1', 'In'), ('0', 'Out')], max_length=1)),
                ('unrestrictUse', models.IntegerField(default=0)),
                ('blocked', models.IntegerField(default=0)),
                ('qltyInspection', models.IntegerField(default=0)),
                ('time', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.materialitem')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('itemId', models.IntegerField()),
                ('estimatedPrice', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('deliveryDate', models.DateField()),
                ('status', models.CharField(choices=[('0', 'Requisition Created'), ('1', 'Order Created')], default='0', max_length=1)),
                ('meterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.materialitem')),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.purchaserequisition')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('euser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.euser')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('deadline', models.DateField()),
                ('deliveryDate', models.DateField()),
                ('collNo', models.CharField(max_length=10)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('validTime', models.DateField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('rej', models.BooleanField(blank=True, null=True)),
                ('euser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.euser')),
                ('ri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.requisitionitem')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telephone', models.CharField(max_length=11, validators=[MM.models.validate_phone])),
                ('fax', models.CharField(max_length=10, validators=[MM.models.validate_digit])),
                ('shippingAddress', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('euser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.euser')),
                ('rfq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MM.quotation')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('itemId', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('deliveryDate', models.DateField()),
                ('price', models.IntegerField()),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('0', 'Not Deliveried'), ('1', 'Deliveried'), ('2', 'Invoice Received'), ('4', 'Payoff Completed')], default='0', max_length=1)),
                ('qualityScore', models.IntegerField(blank=True, null=True)),
                ('serviceScore', models.IntegerField(blank=True, null=True)),
                ('quantityScore', models.IntegerField(blank=True, null=True)),
                ('ontimeScore', models.IntegerField(blank=True, null=True)),
                ('meterialItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.materialitem')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.purchaseorder')),
            ],
        ),
        migrations.AddField(
            model_name='materialitem',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.stock'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fiscal', models.CharField(max_length=4)),
                ('sumAmount', models.IntegerField()),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('text', models.TextField(blank=True, max_length=100, null=True)),
                ('invoiceDate', models.DateField()),
                ('postDate', models.DateField()),
                ('euser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.euser')),
                ('orderItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='GoodReceipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actualQnty', models.IntegerField()),
                ('sType', models.CharField(max_length=1)),
                ('time', models.DateField()),
                ('postTime', models.DateField()),
                ('euser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.euser')),
                ('orderItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('euser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.euser')),
            ],
        ),
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('glAccount', models.CharField(max_length=6)),
                ('type', models.CharField(choices=[('0', 'Credit'), ('1', 'Debt')], max_length=1)),
                ('amount', models.IntegerField()),
                ('gr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MM.goodreceipt')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MM.invoice')),
                ('je', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.account')),
            ],
        ),
    ]
