# Generated by Django 4.0.5 on 2022-08-02 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('vname', models.CharField(max_length=20, unique=True)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=10)),
                ('glAcount', models.CharField(max_length=6)),
                ('tpType', models.IntegerField()),
                ('complanyCode', models.CharField(max_length=4)),
                ('currency', models.CharField(max_length=10)),
                ('score', models.IntegerField()),
                ('euser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.euser')),
            ],
        ),
    ]
