# Generated by Django 4.0.5 on 2022-08-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0002_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='complanyCode',
            new_name='companyCode',
        ),
    ]
