# Generated by Django 4.0.5 on 2022-08-04 02:14

import MM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0003_rename_complanycode_vendor_companycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='fax',
            field=models.CharField(blank=True, max_length=10, validators=[MM.models.validate_digit]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=11, validators=[MM.models.validate_phone]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='prog',
            field=models.CharField(default='CN00', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='currency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='postcode',
            field=models.CharField(max_length=6, validators=[MM.models.validate_digit]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='score',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='tpType',
            field=models.IntegerField(blank=True),
        ),
    ]
