# Generated by Django 4.0.5 on 2022-08-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0004_vendor_fax_vendor_phone_vendor_prog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='prog',
            new_name='pOrg',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='tpType',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
