# Generated by Django 4.0.5 on 2022-08-06 11:29

import MM.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0005_rename_prog_vendor_porg_alter_vendor_tptype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('JEType', models.CharField(max_length=2)),
                ('sumAmount', models.IntegerField()),
                ('postDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=20, unique=True)),
                ('mType', models.CharField(max_length=5)),
                ('mGroup', models.CharField(max_length=4)),
                ('meaunit', models.CharField(max_length=3)),
                ('netWeight', models.IntegerField(default=0)),
                ('weightUnit', models.CharField(max_length=3)),
                ('transGrp', models.CharField(blank=True, max_length=1)),
                ('loadingGrp', models.CharField(blank=True, max_length=1)),
                ('industrySector', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('0', 'Requisition Created'), ('1', 'Order Created')], default='0', max_length=1)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('euser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.euser')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.CharField(default='MIDEA', max_length=20)),
                ('companyCode', models.CharField(max_length=4)),
                ('pOrg', models.CharField(max_length=4)),
                ('pGrp', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='vendor',
            name='score',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('1', 'In'), ('0', 'Out')], max_length=1)),
                ('unrestrictUse', models.IntegerField(default=0)),
                ('blocked', models.IntegerField(default=0)),
                ('qltyInspection', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.material')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('itemId', models.IntegerField()),
                ('estimatedPrice', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('deliveryDate', models.DateField()),
                ('meterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.material')),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.purchaserequisition')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('euser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.euser')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('deadline', models.DateField()),
                ('deliveryDate', models.DateField()),
                ('collNo', models.CharField(max_length=10)),
                ('price', models.IntegerField(blank=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('validTime', models.DateField(blank=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('euser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.euser')),
                ('ri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.requisitionitem')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telephone', models.CharField(max_length=11, validators=[MM.models.validate_phone])),
                ('fax', models.CharField(max_length=10, validators=[MM.models.validate_digit])),
                ('shippingAddress', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('euser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.euser')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.quotation')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('itemId', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('deliveryDate', models.DateField()),
                ('price', models.IntegerField()),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('0', 'Not Deliveried'), ('1', 'Deliveried'), ('2', 'Invoice Received'), ('4', 'Payoff Completed')], default='0', max_length=1)),
                ('qualityScore', models.IntegerField(blank=True)),
                ('serviceScore', models.IntegerField(blank=True)),
                ('meterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.material')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sloc', models.CharField(max_length=4)),
                ('sOrg', models.CharField(max_length=4)),
                ('distrChannel', models.CharField(choices=[('I', 'IN'), ('W', 'WH')], max_length=1)),
                ('unrestrictUse', models.IntegerField(default=0)),
                ('blocked', models.IntegerField(default=0)),
                ('qltyInspection', models.IntegerField(default=0)),
                ('transit', models.IntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.material')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fiscal', models.CharField(max_length=4)),
                ('sumAmount', models.IntegerField()),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('text', models.TextField(blank=True, max_length=100)),
                ('invoiceDate', models.DateField()),
                ('postDate', models.DateField()),
                ('euser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.euser')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='GoodReceipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actualQnty', models.IntegerField()),
                ('sType', models.CharField(max_length=1)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('postTime', models.DateTimeField()),
                ('euser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.euser')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('euser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.euser')),
            ],
        ),
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('glAccount', models.CharField(max_length=6)),
                ('type', models.CharField(choices=[('0', 'Credit'), ('1', 'Debt')], max_length=1)),
                ('amount', models.IntegerField()),
                ('je', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='gr',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='MM.goodreceipt'),
        ),
        migrations.AddField(
            model_name='account',
            name='invoice',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='MM.invoice'),
        ),
    ]
