# Generated by Django 4.0.5 on 2022-08-11 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0006_account_material_purchaserequisition_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='gr',
        ),
        migrations.RemoveField(
            model_name='account',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='status',
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='gr',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='MM.goodreceipt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='invoice',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='MM.invoice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ontimeScore',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantityScore',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='rej',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='status',
            field=models.CharField(choices=[('0', 'Requisition Created'), ('1', 'Order Created')], default='0', max_length=1),
        ),
    ]
