# Generated by Django 4.0.5 on 2022-08-13 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0008_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='euser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MM.euser'),
            preserve_default=False,
        ),
    ]
