# Generated by Django 4.0.5 on 2022-08-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0010_remove_stockhistory_material_stockhistory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='shortText',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='mname',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
