# Generated by Django 4.0.5 on 2022-08-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0011_material_shorttext_alter_material_mname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='ontimeScore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qualityScore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantityScore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='serviceScore',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
