# Generated by Django 4.0.5 on 2022-08-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0012_alter_orderitem_ontimescore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='companyCode',
            field=models.CharField(max_length=10),
        ),
    ]
