# Generated by Django 4.0.5 on 2022-08-18 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0015_alter_orderitem_meterial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='meterial',
            new_name='meterialItem',
        ),
        migrations.RemoveField(
            model_name='goodreceipt',
            name='po',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='po',
        ),
        migrations.AddField(
            model_name='goodreceipt',
            name='orderItem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MM.orderitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='orderItem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MM.orderitem'),
            preserve_default=False,
        ),
    ]
