# Generated by Django 4.0.5 on 2022-08-18 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0016_rename_meterial_orderitem_meterialitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='gr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MM.goodreceipt'),
        ),
        migrations.AlterField(
            model_name='accountdetail',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MM.invoice'),
        ),
        migrations.AlterField(
            model_name='goodreceipt',
            name='postTime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='goodreceipt',
            name='time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
