# Generated by Django 4.0.5 on 2022-08-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0017_alter_accountdetail_gr_alter_accountdetail_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='mname',
            field=models.CharField(max_length=5),
        ),
    ]
