# Generated by Django 4.0.5 on 2022-08-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0018_alter_material_mname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='mname',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
