# Generated by Django 4.0.5 on 2022-08-20 09:29

import MM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0019_alter_material_mname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='text',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='loadingGrp',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='transGrp',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='text',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='rej',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='validTime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='fax',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[MM.models.validate_digit]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[MM.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='tpType',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
