# Generated by Django 4.0.5 on 2022-08-21 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0020_alter_invoice_currency_alter_invoice_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='rfq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MM.quotation'),
        ),
    ]
