# Generated by Django 4.0.5 on 2022-08-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0021_alter_purchaseorder_rfq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='shortText',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
